config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges

  post 'downgrade', to: 'welcome#downgrade'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis
  has_many :collaborators, dependent: :destroy

  after_initialize { self.role ||= :standard }

  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]

  def collaborator_for(wiki)
    collaborators.where(wiki_id: wiki.id).first
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 1500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Premium Membership',
      :currency    => 'usd'
    )

    update_role(customer.email)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private
  def update_role(email)
    User.find_by_email(email).premium!
  end

  def downgrade_role
    current_user.standard!
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Collaborator.new
  end

  def create
    collaborator_user = User.find_by_email(params[:collaborator])
    wiki = Wiki.find(params[:wiki_id])
    if wiki.collaborators.exists?(user_id: collaborator_user.id)
      flash[:notice] = "This collaborator was already added."
      redirect_to wiki
    else
      collaborator = Collaborator.new(user_id: collaborator_user.id, wiki_id: wiki.id)
      if collaborator.save
        flash[:notice] = "Collaborator added."
      else
        flash[:alert] = "Failed to add collaborator."
      end
      redirect_to wiki
    end
  end

  def destroy
    wiki = Wiki.find(params[:wiki_id])
    collaborator = Collaborator.find(params[:id])
    collaborator_user = User.find(collaborator.user_id)

    if collaborator.destroy
      flash[:notice] = "Collaborator removed."
    else
      flash[:alert] = "Failed to remove collaborator."
    end
    redirect_to wiki
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def downgrade
    current_user.wikis.each do |wiki|
      wiki.private = nil
    end
    current_user.standard!
    redirect_to root_path
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!

  before_action :auth_user, only: [:show, :edit, :update]
  before_action :auth_premium, only: [:destroy]

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.create(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update!(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to :wikis
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def auth_user
    wiki = Wiki.find(params[:id])

    unless current_user.admin? || !wiki.private || current_user == wiki.user || wiki.collaborators.exists?(user_id: current_user.id)
      flash[:alert] = "You do not have access to that option."
      redirect_to wiki_path
    end
  end

  def auth_premium
    wiki = Wiki.find(params[:id])

    unless current_user.admin? || current_user == wiki.user
      flash[:alert] = "You do not have access to that option."
      redirect_to wiki_path
    end
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
     content_tag :div, capture(&block), class: css_class
   end

   def markdown(text)
     options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_delete?(wiki)
    current_user == wiki.user || current_user.admin?
  end

  def user_is_authorized_for_private?
    current_user.premium? || current_user.admin?
  end
end

app/views/charges/create.html.erb
<div class="jumbotron">
  <h2>Thanks, you paid <strong>$15.00</strong>!</h2>
  <h4>You are now a <strong>Premium</strong> member and can create private wikis.</h4>
  <p><%= link_to "Start Using Premium Features!", root_path, class: 'btn btn-success' %></p>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $15.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Premium Subscription"
          data-amount="1500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to "Blocipedia", root_path %></li>
        <li class="nav-item"><%= link_to "Wikis", wikis_path %></li>

        <% if user_signed_in? %>
          <li class="nav-item pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
          <li class="nav-item pull-right"><%= link_to "Edit profile", edit_user_registration_path %></li>
          <li class="nav-item pull-right">Signed in as: <strong><%= current_user.email %></strong> | </li>
        <% else %>
          <li class="nav-item pull-right"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-item pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>

      <% if flash[:notice] %>
         <div class="alert alert-success">
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <%= flash[:alert] %>
         </div>
       <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="welcome">
  <h1>Blocipedia: Social, Markdown Wikis</h1>
  <div class="jumbotron">
    <h3>Create and share Markdown Wikis</h3>
    <p>
      <% if !current_user %>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-success' %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>
      <% if current_user && current_user.premium? %>
        <%= link_to "Return to Free", downgrade_path, method: :post, data: { confirm: 'Are you sure you want to return to free? All your private wikis will become public.' }, class: 'btn btn-primary' %>
      <% end %>
      <% if current_user && current_user.standard? %>
        <%= link_to "Upgrade to Premium!", new_charge_path, class: 'btn btn-success' %>
      <% end %>
    </p>
  </div>
  <div class="col-md-6">
    <h4>Create as many public <br /> wikis as you want!</h4>
    <h1><%= fa_icon "users" %></h1>
    <h4>Free Plan</h4>
  </div>
  <div class="col-md-6">
    <h4>Create private wikis!</h4>
    <h1><%= fa_icon "user" %></h1>
    <h4>Premium Plan</h4>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %></h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <hr />
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_group_tag(wiki.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title" %>
    <% end %>

    <%= form_group_tag(wiki.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', placeholder: "Enter Wiki Body" %>
    <% end %>

    <% if user_is_authorized_for_private? && wiki.id == nil %>
      <div class="form-group">
        <%= f.label :private , class: 'checkbox' do %>
          <%= f.check_box :private %> Private Wiki
        <% end %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/wikis/index.html.erb
<h1>My Wikis</h1>

<table class="table">
  <tbody>
    <% current_user.wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
        <td><%= link_to "edit", edit_wiki_path(wiki.id), class: 'btn btn-success' %></td>
        <td><%= link_to "delete", wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>My Collaborated Wikis</h1>

<table class="table">
  <tbody>
    <% @wikis.each do |wiki| %>
      <% wiki.collaborators.each do |collaborator| %>
        <% if collaborator.user_id == current_user.id %>
          <tr>
            <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
            <td><%= link_to "edit", edit_wiki_path(wiki.id), class: 'btn btn-success' %></td>
            <td><%= link_to "delete", wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>


<h1>All Wikis</h1>

<table class="table">
  <tbody>
    <% @wikis.each do |wiki| %>
      <% if !wiki.private && wiki.user_id != current_user.id %>
        <tr>
          <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
          <td><%= link_to "edit", edit_wiki_path(wiki.id), class: 'btn btn-success' %></td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td><%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %></td>
    </tr>
  </tbody>
</table>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %> </h1>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= "#{@wiki.user.email}" %>
  </small>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
<div class="col-md-4">
  <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% if user_is_authorized_for_delete?(@wiki) %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>
</div>